#include "spark/evaluator.h"
#include "spark/parser.h"

#include "evaluator_parts/01_helpers.cpp"

#include "phase5/runtime/value_constructors.cpp"
#include "phase5/runtime/value_repr.cpp"
#include "phase5/runtime/index_eval.cpp"
#include "phase5/runtime/index_assign.cpp"
#include "phase5/runtime/environment.cpp"
#include "phase5/runtime/interpreter_core.cpp"
#include "phase5/runtime/interpreter_ops.cpp"
#include "phase6/runtime/01_hetero_plan_common.cpp"
#include "phase6/runtime/02_hetero_list_ops.cpp"
#include "phase6/runtime/03_hetero_matrix_ops.cpp"
#include "phase7/runtime/01_pipeline_types.cpp"
#include "phase7/runtime/02_pipeline_parse.cpp"
#include "phase7/runtime/03_pipeline_exec_list.cpp"
#include "phase7/runtime/04_pipeline_exec_matrix.cpp"
#include "phase7/runtime/05_pipeline_entry.cpp"
#include "phase8/runtime/01_schedule.cpp"
#include "phase8/runtime/02_pack_cache.cpp"
#include "phase8/runtime/03_matmul_kernel.cpp"
#include "phase8/runtime/04_matmul_entry.cpp"

#include "evaluator_parts/expr/expr_number.cpp"
#include "evaluator_parts/expr/expr_bool.cpp"
#include "evaluator_parts/expr/expr_variable.cpp"
#include "evaluator_parts/expr/expr_list.cpp"
#include "evaluator_parts/expr/expr_unary.cpp"
#include "evaluator_parts/expr/expr_binary.cpp"
#include "evaluator_parts/expr/expr_call.cpp"
#include "evaluator_parts/expr/expr_attribute.cpp"
#include "evaluator_parts/expr/expr_index.cpp"

#include "evaluator_parts/stmt/stmt_expression.cpp"
#include "evaluator_parts/stmt/stmt_assign.cpp"
#include "evaluator_parts/stmt/stmt_return.cpp"
#include "evaluator_parts/stmt/stmt_if.cpp"
#include "evaluator_parts/stmt/stmt_while.cpp"
#include "evaluator_parts/stmt/stmt_for.cpp"
#include "evaluator_parts/stmt/stmt_function.cpp"
#include "evaluator_parts/stmt/stmt_class.cpp"

#include "evaluator_parts/eval_dispatch.cpp"
