#include "spark/evaluator.h"
#include "spark/parser.h"

// NOTE(architecture):
// evaluator.cpp intentionally uses a unity-style aggregation of phase runtime units.
// This keeps hot runtime paths in one translation unit for inlining/perf stability.
// Layer boundaries are still represented by directory ownership; shared contracts are
// routed through internal_helpers.h to avoid copy/paste drift.

#include "evaluator_parts/01_helpers.cpp"

#include "scalar_runtime/runtime/value_constructors.cpp"
#include "scalar_runtime/runtime/value_repr.cpp"
#include "scalar_runtime/runtime/index_eval.cpp"
#include "scalar_runtime/runtime/index_assign.cpp"
#include "scalar_runtime/runtime/environment.cpp"
#include "scalar_runtime/runtime/primitives/01_numeric_scalar_core.cpp"
#include "scalar_runtime/runtime/primitives/02_numeric_builtin_registry.cpp"
#include "scalar_runtime/runtime/interpreter_core.cpp"
#include "scalar_runtime/runtime/ops/ops_common_numeric.cpp"
#include "scalar_runtime/runtime/ops/ops_list_arithmetic.cpp"
#include "scalar_runtime/runtime/ops/ops_matrix_arithmetic.cpp"
#include "scalar_runtime/runtime/ops/controllers/01_ops_controller_core.cpp"
#include "scalar_runtime/runtime/ops/controllers/02_ops_controller_containers.cpp"
#include "scalar_runtime/runtime/ops/controllers/03_ops_controller_scalar.cpp"
#include "scalar_runtime/runtime/ops/controllers/04_ops_controller_orchestrator.cpp"
#include "scalar_runtime/runtime/interpreter_ops.cpp"
#include "hetero_runtime/runtime/01_hetero_plan_common.cpp"
#include "hetero_runtime/runtime/02_hetero_list_ops.cpp"
#include "hetero_runtime/runtime/03_hetero_matrix_ops.cpp"
#include "stream_pipeline/runtime/01_pipeline_types.cpp"
#include "stream_pipeline/runtime/02_pipeline_parse.cpp"
#include "stream_pipeline/runtime/03_pipeline_exec_list.cpp"
#include "stream_pipeline/runtime/04_pipeline_exec_matrix.cpp"
#include "stream_pipeline/runtime/05_pipeline_entry.cpp"
#include "schedule_gpu/runtime/01_schedule.cpp"
#include "schedule_gpu/runtime/02_pack_cache.cpp"
#include "schedule_gpu/runtime/03_matmul_kernel.cpp"
#include "schedule_gpu/runtime/04_matmul_entry.cpp"
#include "schedule_gpu/runtime/05_gpu_interface_orchestrator.cpp"
#include "async_runtime/runtime/01_scheduler.cpp"
#include "async_runtime/runtime/02_task_runtime.cpp"
#include "async_runtime/runtime/03_channel_runtime.cpp"
#include "async_runtime/runtime/04_parallel_runtime.cpp"
#include "async_runtime/runtime/05_stream_runtime.cpp"

#include "evaluator_parts/expr/expr_number.cpp"
#include "evaluator_parts/expr/expr_string.cpp"
#include "evaluator_parts/expr/expr_bool.cpp"
#include "evaluator_parts/expr/expr_variable.cpp"
#include "evaluator_parts/expr/expr_list.cpp"
#include "evaluator_parts/expr/expr_unary.cpp"
#include "evaluator_parts/expr/expr_binary.cpp"
#include "evaluator_parts/expr/expr_call.cpp"
#include "evaluator_parts/expr/expr_attribute.cpp"
#include "evaluator_parts/expr/expr_index.cpp"

#include "evaluator_parts/stmt/stmt_expression.cpp"
#include "evaluator_parts/stmt/stmt_assign.cpp"
#include "evaluator_parts/stmt/stmt_return.cpp"
#include "evaluator_parts/stmt/stmt_break.cpp"
#include "evaluator_parts/stmt/stmt_continue.cpp"
#include "evaluator_parts/stmt/stmt_if.cpp"
#include "evaluator_parts/stmt/stmt_switch.cpp"
#include "evaluator_parts/stmt/stmt_try_catch.cpp"
#include "evaluator_parts/stmt/stmt_while.cpp"
#include "evaluator_parts/stmt/stmt_for.cpp"
#include "evaluator_parts/stmt/stmt_function.cpp"
#include "evaluator_parts/stmt/stmt_class.cpp"
#include "evaluator_parts/stmt/stmt_with_task_group.cpp"

#include "evaluator_parts/expr_controllers/01_expr_controller_core.cpp"

#include "evaluator_parts/stmt_controllers/01_stmt_controller_core.cpp"
#include "evaluator_parts/stmt_controllers/02_stmt_controller_control_flow.cpp"
#include "evaluator_parts/stmt_controllers/03_stmt_controller_definition.cpp"
#include "evaluator_parts/stmt_controllers/04_stmt_controller_orchestrator.cpp"

#include "evaluator_parts/eval_dispatch.cpp"
